### ISSUE TITLE
App crash on Sending Tari

### ISSUE THREAD

**Issue by philipr-za** [tari-project/wallet-android#239]
App crashes when sending Tari with the following crash log:
```
	
1:12 PM



2020-03-29 13:09:36.984 30004-30188/? D/FFI: 2020-03-29 13:09:36.984367722] wallet::output_manager_service] ERROR Error handling request: OutputManagerStorageError(DuplicateOutput)
2020-03-29 13:09:36.984 30004-30188/? D/FFI: 2020-03-29 13:09:36.984489649] wallet_ffi::error] ERROR OutputManagerError(OutputManagerStorageError(DuplicateOutput))
2020-03-29 13:09:36.986 30004-31249/? E/AndroidRuntime: FATAL EXCEPTION: Thread-12
    Process: com.tari.android.wallet, PID: 30004
    com.tari.android.wallet.ffi.FFIException
        at com.tari.android.wallet.ffi.FFIExceptionKt.throwIf(FFIException.kt:43)
        at com.tari.android.wallet.ffi.FFIWallet.importUTXO(FFIWallet.kt:606)
        at com.tari.android.wallet.service.WalletService$TariWalletServiceImpl.importTestnetUTXO(WalletService.kt:790)
        at com.tari.android.wallet.ui.activity.home.HomeActivity.importSecondUTXO(HomeActivity.kt:997)
        at com.tari.android.wallet.ui.activity.home.HomeActivity.access$importSecondUTXO(HomeActivity.kt:99)
        at com.tari.android.wallet.ui.activity.home.HomeActivity$onSendTxSuccessful$3.run(HomeActivity.kt:990)
        at java.lang.Thread.run(Thread.java:919)
```

It looks like the app is trying to Import the Second UTXO which has already been imported on app restart. The backend reports it is a duplicate import and this crash occurs.

**Comment by philipr-za** [comment]
We pinpointed the issue in the FFI, working on downstream fix
